const data = [
  {
    key: 0,
    rarity: 3,
    ship: ['Admiral'],
    name: 'Admiral Mura',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/69785831',
      status: 200,
    },
    file: '3_admiral_mura',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_admiral_mura.jpg',
  },
  {
    key: 1,
    rarity: 3,
    ship: ['Abyssal'],
    name: 'Air Defense Hime',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/68790083',
      status: 200,
    },
    file: '3_air_defense_hime',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_air_defense_hime.jpg',
  },
  {
    key: 2,
    rarity: 3,
    ship: ['Yamashiro'],
    name: 'Bashful Yamashiro',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58024565',
      status: 200,
    },
    file: '3_bashful_yamashiro',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_bashful_yamashiro.jpg',
  },
  {
    key: 3,
    rarity: 3,
    ship: ['Admiral', 'Asagumo', 'Fusou', 'Michishio', 'Yamagumo', 'Yamashiro'],
    name: 'Battle Of Surigao Strait',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/50347932',
      status: 200,
    },
    file: '3_battle_of_surigao_strait',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_battle_of_surigao_strait.jpg',
  },
  {
    key: 4,
    rarity: 3,
    ship: ['Mutsu', 'Nagato'],
    name: 'Beach Secretaries',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/52404675',
      status: 200,
    },
    file: '3_beach_secretaries',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_beach_secretaries.jpg',
  },
  {
    key: 5,
    rarity: 3,
    ship: ['Naganami'],
    name: 'Break For Bubble Tea',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76354107',
      status: 200,
    },
    file: '3_break_for_bubble_tea',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_break_for_bubble_tea.jpg',
  },
  {
    key: 6,
    rarity: 3,
    ship: ['Shoukaku', 'Zuikaku'],
    name: 'Cardiv 5 Maids',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58293199',
      status: 200,
    },
    file: '3_cardiv_5_maids',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_cardiv_5_maids.jpg',
  },
  {
    key: 7,
    rarity: 3,
    ship: ['Shigure'],
    name: 'Date With Shigure',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/60380013',
      status: 200,
    },
    file: '3_date_with_shigure',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_date_with_shigure.jpg',
  },
  {
    key: 8,
    rarity: 3,
    ship: ['I-58'],
    name: 'Dechi Note',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48569125',
      status: 200,
    },
    file: '3_dechi_note',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_dechi_note.jpg',
  },
  {
    key: 9,
    rarity: 3,
    ship: ['Akigumo', 'Kazagumo'],
    name: 'Doujin Circle Autumn Cloud',
    source: {
      type: 'nicovideo',
      url: 'https://seiga.nicovideo.jp/seiga/im8934535',
      status: 200,
    },
    file: '3_doujin_circle_autumn_cloud',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_doujin_circle_autumn_cloud.jpg',
  },
  {
    key: 10,
    rarity: 3,
    ship: ['Abyssal'],
    name: 'European Hime',
    source: {
      type: 'nicovideo',
      url: 'https://seiga.nicovideo.jp/seiga/im6992439',
      status: 200,
    },
    file: '3_european_hime',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_european_hime.jpg',
  },
  {
    key: 11,
    rarity: 3,
    ship: ['Admiral', 'Hibiki', 'Inazuma'],
    name: 'Kamio Reiji',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/65462198',
      status: 200,
    },
    file: '3_kamio_reiji',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_kamio_reiji.jpg',
  },
  {
    key: 12,
    rarity: 3,
    ship: ['Asashimo', 'Ashigara', 'Kasumi', 'Kiyoshimo', 'Ooyodo'],
    name: 'Kimura Raiding Force',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58346231',
      status: 200,
    },
    file: '3_kimura_raiding_force',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_kimura_raiding_force.jpg',
  },
  {
    key: 13,
    rarity: 3,
    ship: ['Admiral'],
    name: 'Narumi Tsuyu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/52198198',
      status: 200,
    },
    file: '3_narumi_tsuyu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_narumi_tsuyu.jpg',
  },
  {
    key: 14,
    rarity: 3,
    ship: ['Asagumo', 'Fusou', 'Michishio', 'Mogami', 'Shigure', 'Yamagumo', 'Yamashiro'],
    name: 'Nishimura Fleet',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/66469254',
      status: 200,
    },
    file: '3_nishimura_fleet',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_nishimura_fleet.jpg',
  },
  {
    key: 15,
    rarity: 3,
    ship: ['Akagi'],
    name: 'Onee-sie Akagi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48453671',
      status: 200,
    },
    file: '3_onee-sie_akagi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_onee-sie_akagi.jpg',
  },
  {
    key: 16,
    rarity: 3,
    ship: ['Kasumi'],
    name: 'Operation Ten-go',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54814831',
      status: 404,
    },
    file: '3_operation_ten-go',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_operation_ten-go.jpg',
  },
  {
    key: 17,
    rarity: 3,
    ship: ['Shimakaze'],
    name: 'Schoolday Shimakaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/39406050',
      status: 200,
    },
    file: '3_schoolday_shimakaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_schoolday_shimakaze.jpg',
  },
  {
    key: 18,
    rarity: 3,
    ship: ['Shiranui'],
    name: 'Shiranui Sparkle',
    source: {
      type: 'ebihurya332',
      url: 'https://twitter.com/ebihurya332/status/1171107526705737728',
      status: 200,
    },
    file: '3_shiranui_sparkle',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_shiranui_sparkle.jpg',
  },
  {
    key: 19,
    rarity: 3,
    ship: ['Amatsukaze'],
    name: 'Soda For The Admiral',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/45049727',
      status: 200,
    },
    file: '3_soda_for_the_admiral',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_soda_for_the_admiral.jpg',
  },
  {
    key: 20,
    rarity: 3,
    ship: ['Shimakaze'],
    name: 'Surfing Shimakaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40586032',
      status: 200,
    },
    file: '3_surfing_shimakaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_surfing_shimakaze.jpg',
  },
  {
    key: 21,
    rarity: 3,
    ship: ['Admiral'],
    name: 'T-head Admiral',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/38442034',
      status: 200,
    },
    file: '3_t-head_admiral',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_t-head_admiral.jpg',
  },
  {
    key: 22,
    rarity: 3,
    ship: ['Kaga'],
    name: 'Traditional Dress',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/63793011',
      status: 200,
    },
    file: '3_traditional_dress',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_traditional_dress.jpg',
  },
  {
    key: 23,
    rarity: 3,
    ship: ['Musashi', 'Yamato'],
    name: 'Yamato Class Sisters',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/56478934',
      status: 200,
    },
    file: '3_yamato_class_sisters',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_yamato_class_sisters.jpg',
  },
  {
    key: 24,
    rarity: 3,
    ship: ['Admiral', 'Mochizuki'],
    name: 'Yume No Owari',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58113122',
      status: 200,
    },
    file: '3_yume_no_owari',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/3_yume_no_owari.jpg',
  },
  {
    key: 25,
    rarity: 2,
    ship: ['Hibiki'],
    name: 'Admiral Hibiki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54317550',
      status: 200,
    },
    file: '2_admiral_hibiki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_admiral_hibiki.jpg',
  },
  {
    key: 26,
    rarity: 2,
    ship: ['Agano', 'Noshiro', 'Sakawa', 'Yahagi'],
    name: 'Agano Class',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/979749100047384576',
      status: 200,
    },
    file: '2_agano_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_agano_class.jpg',
  },
  {
    key: 27,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Aircraft Carrier Princess',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/51609463',
      status: 200,
    },
    file: '2_aircraft_carrier_princess',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_aircraft_carrier_princess.jpg',
  },
  {
    key: 28,
    rarity: 2,
    ship: ['Akitsushima'],
    name: 'Akitsushimas Seaplane',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/50783647',
      status: 200,
    },
    file: '2_akitsushimas_seaplane',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_akitsushimas_seaplane.jpg',
  },
  {
    key: 29,
    rarity: 2,
    ship: ['Amatsukaze'],
    name: 'Amatsukaze In Action',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54256793',
      status: 200,
    },
    file: '2_amatsukaze_in_action',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_amatsukaze_in_action.jpg',
  },
  {
    key: 30,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Ancient Destroyer Hime',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/62053675',
      status: 200,
    },
    file: '2_ancient_destroyer_hime',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_ancient_destroyer_hime.jpg',
  },
  {
    key: 31,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Anti-submarine Warfare',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/65480666',
      status: 200,
    },
    file: '2_anti-submarine_warfare',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_anti-submarine_warfare.jpg',
  },
  {
    key: 32,
    rarity: 2,
    ship: ['Arare', 'Arashio', 'Asagumo', 'Asashio', 'Kasumi', 'Michishio', 'Ooshio', 'Yamagumo'],
    name: 'Asashio Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/56744855',
      status: 200,
    },
    file: '2_asashio_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_asashio_class.jpg',
  },
  {
    key: 33,
    rarity: 2,
    ship: ['Atago'],
    name: 'Atago Victory Pose',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55189820',
      status: 200,
    },
    file: '2_atago_victory_pose',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_atago_victory_pose.jpg',
  },
  {
    key: 34,
    rarity: 2,
    ship: ['Kiyoshimo'],
    name: 'Battleship Kiyoshimo',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1111229621331070977',
      status: 404,
    },
    file: '2_battleship_kiyoshimo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_battleship_kiyoshimo.jpg',
  },
  {
    key: 35,
    rarity: 2,
    ship: ['Johnston'],
    name: 'Bikini Johnston',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76540695',
      status: 200,
    },
    file: '2_bikini_johnston',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_bikini_johnston.jpg',
  },
  {
    key: 36,
    rarity: 2,
    ship: ['Ark Royal', 'Bismarck'],
    name: 'Bismarck And Ark Royal',
    source: {
      type: 'nicovideo',
      url: 'https://seiga.nicovideo.jp/seiga/im8786811',
      status: 200,
    },
    file: '2_bismarck_and_ark_royal',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_bismarck_and_ark_royal.jpg',
  },
  {
    key: 37,
    rarity: 2,
    ship: ['Ooyodo'],
    name: 'Bunny Ooyodo',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/67600803',
      status: 200,
    },
    file: '2_bunny_ooyodo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_bunny_ooyodo.jpg',
  },
  {
    key: 38,
    rarity: 2,
    ship: ['Hiryuu', 'Soryuu'],
    name: 'Bunny Soryuu And Hiryuu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/71372485',
      status: 200,
    },
    file: '2_bunny_soryuu_and_hiryuu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_bunny_soryuu_and_hiryuu.jpg',
  },
  {
    key: 39,
    rarity: 2,
    ship: ['Suzutsuki'],
    name: 'Bunnysuit Suzutsuki',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/970322104112459776',
      status: 200,
    },
    file: '2_bunnysuit_suzutsuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_bunnysuit_suzutsuki.jpg',
  },
  {
    key: 40,
    rarity: 2,
    ship: ['Taihou'],
    name: 'Bunnysuit Taihou',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/875344195631759360',
      status: 200,
    },
    file: '2_bunnysuit_taihou',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_bunnysuit_taihou.jpg',
  },
  {
    key: 41,
    rarity: 2,
    ship: ['Aquila', 'Saratoga'],
    name: 'Carrier Maids',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/1126851415014379521',
      status: 200,
    },
    file: '2_carrier_maids',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_carrier_maids.jpg',
  },
  {
    key: 42,
    rarity: 2,
    ship: ['Haruna'],
    name: 'Catgirl Haruna',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/50158780',
      status: 200,
    },
    file: '2_catgirl_haruna',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_catgirl_haruna.jpg',
  },
  {
    key: 43,
    rarity: 2,
    ship: ['Shigure'],
    name: 'Cherry Blossom Shigure',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/73618894',
      status: 200,
    },
    file: '2_cherry_blossom_shigure',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_cherry_blossom_shigure.jpg',
  },
  {
    key: 44,
    rarity: 2,
    ship: ['Chitose', 'Chiyoda'],
    name: 'Chitose Sisters',
    source: {
      type: 'danbooru',
      url: 'https://danbooru.donmai.us/posts/1537448',
      status: 200,
    },
    file: '2_chitose_sisters',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_chitose_sisters.jpg',
  },
  {
    key: 45,
    rarity: 2,
    ship: ['Akigumo', 'Makigumo'],
    name: 'Comiket Visit',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/42005281',
      status: 200,
    },
    file: '2_comiket_visit',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_comiket_visit.jpg',
  },
  {
    key: 46,
    rarity: 2,
    ship: ['Nagato', 'Prinz Eugen', 'Sakawa'],
    name: 'Crossroads Reunion',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/710045170922692609',
      status: 200,
    },
    file: '2_crossroads_reunion',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_crossroads_reunion.jpg',
  },
  {
    key: 47,
    rarity: 2,
    ship: ['Hamakaze', 'Isokaze', 'Tanikaze', 'Urakaze'],
    name: 'Destroyer Division 17',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1085910562624614400',
      status: 200,
    },
    file: '2_destroyer_division_17',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_destroyer_division_17.jpg',
  },
  {
    key: 48,
    rarity: 2,
    ship: ['Arare', 'Kagerou', 'Kasumi', 'Shiranui'],
    name: 'Destroyer Division 18',
    source: {
      type: 'danbooru',
      url: 'https://danbooru.donmai.us/posts/3065477',
      status: 200,
    },
    file: '2_destroyer_division_18',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_destroyer_division_18.jpg',
  },
  {
    key: 49,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Destroyer Hime',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/56198936',
      status: 200,
    },
    file: '2_destroyer_hime',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_destroyer_hime.jpg',
  },
  {
    key: 50,
    rarity: 2,
    ship: ['Admiral', 'Kongou'],
    name: 'Doting On Kongou',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55853361',
      status: 200,
    },
    file: '2_doting_on_kongou',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_doting_on_kongou.jpg',
  },
  {
    key: 51,
    rarity: 2,
    ship: ['Duca degli Abruzzi', 'Giuseppe Garibaldi'],
    name: 'Duca Degli Abruzzi Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76512645',
      status: 200,
    },
    file: '2_duca_degli_abruzzi_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_duca_degli_abruzzi_class.jpg',
  },
  {
    key: 52,
    rarity: 2,
    ship: ['Admiral', 'Shigure', 'Taigei'],
    name: 'End Of Summer',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58769396',
      status: 200,
    },
    file: '2_end_of_summer',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_end_of_summer.jpg',
  },
  {
    key: 53,
    rarity: 2,
    ship: ['Fubuki', 'Hatsuyuki', 'Isonami', 'Miyuki', 'Murakumo', 'Shirayuki', 'Uranami'],
    name: 'Fubuki Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54546573',
      status: 404,
    },
    file: '2_fubuki_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_fubuki_class.jpg',
  },
  {
    key: 54,
    rarity: 2,
    ship: ['Kashima'],
    name: 'Garden Duty Kashima',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58397125',
      status: 200,
    },
    file: '2_garden_duty_kashima',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_garden_duty_kashima.jpg',
  },
  {
    key: 55,
    rarity: 2,
    ship: ['Graf Zeppelin'],
    name: 'Graf Zeppelins Me Time',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54303546',
      status: 200,
    },
    file: '2_graf_zeppelins_me_time',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_graf_zeppelins_me_time.jpg',
  },
  {
    key: 56,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Harbor Summer Princess',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58632284',
      status: 200,
    },
    file: '2_harbor_summer_princess',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_harbor_summer_princess.jpg',
  },
  {
    key: 57,
    rarity: 2,
    ship: ['Haruna'],
    name: 'Haruna Lends A Hand',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54911377',
      status: 200,
    },
    file: '2_haruna_lends_a_hand',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_haruna_lends_a_hand.jpg',
  },
  {
    key: 58,
    rarity: 2,
    ship: ['Hibiki'],
    name: 'Hibikis Cuddly Pet',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/60926319',
      status: 200,
    },
    file: '2_hibikis_cuddly_pet',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_hibikis_cuddly_pet.jpg',
  },
  {
    key: 59,
    rarity: 2,
    ship: ['I-13', 'I-14'],
    name: 'Hitomi And Iyo',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/61715042',
      status: 200,
    },
    file: '2_hitomi_and_iyo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_hitomi_and_iyo.jpg',
  },
  {
    key: 60,
    rarity: 2,
    ship: ['Inazuma'],
    name: 'Inazuma Unleashed',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54984467',
      status: 200,
    },
    file: '2_inazuma_unleashed',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_inazuma_unleashed.jpg',
  },
  {
    key: 61,
    rarity: 2,
    ship: ['Isuzu'],
    name: 'Isuzus Holiday',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/65040818',
      status: 200,
    },
    file: '2_isuzus_holiday',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_isuzus_holiday.jpg',
  },
  {
    key: 62,
    rarity: 2,
    ship: ['Janus', 'Jervis'],
    name: 'Janus And Jervis',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1176822078961381376',
      status: 200,
    },
    file: '2_janus_and_jervis',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_janus_and_jervis.jpg',
  },
  {
    key: 63,
    rarity: 2,
    ship: ['Yura'],
    name: 'Jumping Right In',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53626810',
      status: 200,
    },
    file: '2_jumping_right_in',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_jumping_right_in.jpg',
  },
  {
    key: 64,
    rarity: 2,
    ship: ['Kasumi'],
    name: 'Kasumi On The Beach',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1129915398474743809',
      status: 200,
    },
    file: '2_kasumi_on_the_beach',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_kasumi_on_the_beach.jpg',
  },
  {
    key: 65,
    rarity: 2,
    ship: ['Kongou'],
    name: 'Kongou Barrage',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55501143',
      status: 200,
    },
    file: '2_kongou_barrage',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_kongou_barrage.jpg',
  },
  {
    key: 66,
    rarity: 2,
    ship: ['Haruna', 'Hiei', 'Kirishima', 'Kongou'],
    name: 'Kongou Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40143576',
      status: 404,
    },
    file: '2_kongou_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_kongou_class.jpg',
  },
  {
    key: 67,
    rarity: 2,
    ship: ['Kiso', 'Kitakami', 'Kuma', 'Ooi', 'Tama'],
    name: 'Kuma Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/64171933',
      status: 200,
    },
    file: '2_kuma_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_kuma_class.jpg',
  },
  {
    key: 68,
    rarity: 2,
    ship: ['Kumano', 'Suzuya'],
    name: 'Kumano And Suzuya',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40229390',
      status: 200,
    },
    file: '2_kumano_and_suzuya',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_kumano_and_suzuya.jpg',
  },
  {
    key: 69,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Light Cruiser Oni',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55627486',
      status: 200,
    },
    file: '2_light_cruiser_oni',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_light_cruiser_oni.jpg',
  },
  {
    key: 70,
    rarity: 2,
    ship: ['Hamakaze'],
    name: 'Light Snack',
    source: {
      type: 'kirishina_maru',
      url: 'https://twitter.com/kirishina_maru/status/932023203001655297',
      status: 200,
    },
    file: '2_light_snack',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_light_snack.jpg',
  },
  {
    key: 71,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Like Royalty',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/73995187',
      status: 200,
    },
    file: '2_like_royalty',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_like_royalty.jpg',
  },
  {
    key: 72,
    rarity: 2,
    ship: ['Maikaze', 'Nowaki'],
    name: 'Maikaze And Nowaki',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/537254029898686465',
      status: 200,
    },
    file: '2_maikaze_and_nowaki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_maikaze_and_nowaki.jpg',
  },
  {
    key: 73,
    rarity: 2,
    ship: ['Admiral'],
    name: 'Mangaka Admiral',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/51860149',
      status: 200,
    },
    file: '2_mangaka_admiral',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_mangaka_admiral.jpg',
  },
  {
    key: 74,
    rarity: 2,
    ship: ['Maruyu'],
    name: 'Maruyu-san',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/45062108',
      status: 200,
    },
    file: '2_maruyu-san',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_maruyu-san.jpg',
  },
  {
    key: 75,
    rarity: 2,
    ship: ['Maya'],
    name: 'Maya Kai Ni',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55974701',
      status: 200,
    },
    file: '2_maya_kai_ni',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_maya_kai_ni.jpg',
  },
  {
    key: 76,
    rarity: 2,
    ship: ['Chitose'],
    name: 'Moonlight Chitose',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/43876295',
      status: 200,
    },
    file: '2_moonlight_chitose',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_moonlight_chitose.jpg',
  },
  {
    key: 77,
    rarity: 2,
    ship: ['Fumizuki', 'Kikuzuki', 'Kisaragi', 'Mikazuki', 'Minazuki', 'Mochizuki', 'Mutsuki', 'Nagatsuki', 'Satsuki', 'Uzuki', 'Yayoi'],
    name: 'Mutsuki Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/62619556',
      status: 200,
    },
    file: '2_mutsuki_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_mutsuki_class.jpg',
  },
  {
    key: 78,
    rarity: 2,
    ship: ['Ashigara', 'Haguro', 'Myoukou', 'Nachi'],
    name: 'Myoukou Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/68766524',
      status: 200,
    },
    file: '2_myoukou_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_myoukou_class.jpg',
  },
  {
    key: 79,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Northern Imouto',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/74892478',
      status: 200,
    },
    file: '2_northern_imouto',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_northern_imouto.jpg',
  },
  {
    key: 80,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'Pacific Princess',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/75304671',
      status: 200,
    },
    file: '2_pacific_princess',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_pacific_princess.jpg',
  },
  {
    key: 81,
    rarity: 2,
    ship: ['Hiei', 'Isokaze'],
    name: 'Poison Cooking',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/50585009',
      status: 200,
    },
    file: '2_poison_cooking',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_poison_cooking.jpg',
  },
  {
    key: 82,
    rarity: 2,
    ship: ['Ro-500'],
    name: 'Ro-500 Assault',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76250917',
      status: 200,
    },
    file: '2_ro-500_assault',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_ro-500_assault.jpg',
  },
  {
    key: 83,
    rarity: 2,
    ship: ['Ark Royal', 'Warspite'],
    name: 'Royalties',
    source: {
      type: 'danbooru',
      url: 'https://danbooru.donmai.us/posts/3107693',
      status: 200,
    },
    file: '2_royalties',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_royalties.jpg',
  },
  {
    key: 84,
    rarity: 2,
    ship: ['Ryuujou'],
    name: 'Ryuujous Day Off',
    source: {
      type: 'wotake_fox',
      url: 'https://twitter.com/wotake_fox/status/969925595344728064',
      status: 200,
    },
    file: '2_ryuujous_day_off',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_ryuujous_day_off.jpg',
  },
  {
    key: 85,
    rarity: 2,
    ship: ['Uzuki'],
    name: 'Sanma Uzuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/71934438',
      status: 200,
    },
    file: '2_sanma_uzuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_sanma_uzuki.jpg',
  },
  {
    key: 86,
    rarity: 2,
    ship: ['Kaga', 'Zuikaku'],
    name: 'Secret Friends',
    source: {
      type: 'zakii03',
      url: 'https://twitter.com/zakii03/status/982257778419888130',
      status: 200,
    },
    file: '2_secret_friends',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_secret_friends.jpg',
  },
  {
    key: 87,
    rarity: 2,
    ship: ['Sendai'],
    name: 'Send-ice To Sendai',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/75762812',
      status: 200,
    },
    file: '2_send-ice_to_sendai',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_send-ice_to_sendai.jpg',
  },
  {
    key: 88,
    rarity: 2,
    ship: ['Harusame', 'Kawakaze', 'Murasame', 'Samidare', 'Shigure', 'Shiratsuyu', 'Suzukaze', 'Umikaze', 'Yamakaze', 'Yuudachi'],
    name: 'Shiratsuyu Class',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/73080009',
      status: 200,
    },
    file: '2_shiratsuyu_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_shiratsuyu_class.jpg',
  },
  {
    key: 89,
    rarity: 2,
    ship: ['Shoukaku'],
    name: 'Shoukaku Shrine Visit',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53671536',
      status: 200,
    },
    file: '2_shoukaku_shrine_visit',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_shoukaku_shrine_visit.jpg',
  },
  {
    key: 90,
    rarity: 2,
    ship: ['Shoukaku', 'Zuikaku'],
    name: 'Shoukaku-class Carriers',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/42685076',
      status: 200,
    },
    file: '2_shoukaku-class_carriers',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_shoukaku-class_carriers.jpg',
  },
  {
    key: 91,
    rarity: 2,
    ship: ['Yamato'],
    name: 'Snow Yamato',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40988309',
      status: 200,
    },
    file: '2_snow_yamato',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_snow_yamato.jpg',
  },
  {
    key: 92,
    rarity: 2,
    ship: ['Tenryuu'],
    name: 'Solemn Tenryuu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53543395',
      status: 200,
    },
    file: '2_solemn_tenryuu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_solemn_tenryuu.jpg',
  },
  {
    key: 93,
    rarity: 2,
    ship: ['Gangut', 'Hibiki', 'Tashkent'],
    name: 'Soviet Comrades',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/68291584',
      status: 200,
    },
    file: '2_soviet_comrades',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_soviet_comrades.jpg',
  },
  {
    key: 94,
    rarity: 2,
    ship: ['Gotland'],
    name: 'Starter Ship Gotland',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1154868767878332416',
      status: 200,
    },
    file: '2_starter_ship_gotland',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_starter_ship_gotland.jpg',
  },
  {
    key: 95,
    rarity: 2,
    ship: ['Suzutsuki'],
    name: 'Suzutsuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/65004850',
      status: 200,
    },
    file: '2_suzutsuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_suzutsuki.jpg',
  },
  {
    key: 96,
    rarity: 2,
    ship: ['Kasumi'],
    name: 'Swimsuit Kasumi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76004343',
      status: 200,
    },
    file: '2_swimsuit_kasumi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_swimsuit_kasumi.jpg',
  },
  {
    key: 97,
    rarity: 2,
    ship: ['Murasame'],
    name: 'Swimsuit Murasame',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76773313',
      status: 200,
    },
    file: '2_swimsuit_murasame',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_swimsuit_murasame.jpg',
  },
  {
    key: 98,
    rarity: 2,
    ship: ['Kamikaze'],
    name: 'Sword Maiden Kamikaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/56747514',
      status: 404,
    },
    file: '2_sword_maiden_kamikaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_sword_maiden_kamikaze.jpg',
  },
  {
    key: 99,
    rarity: 2,
    ship: ['Tsushima'],
    name: 'The Ghost Of Tsushima',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/68771066',
      status: 200,
    },
    file: '2_the_ghost_of_tsushima',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_the_ghost_of_tsushima.jpg',
  },
  {
    key: 100,
    rarity: 2,
    ship: ['Matsukaze'],
    name: 'Travel Partners',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76332793',
      status: 200,
    },
    file: '2_travel_partners',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_travel_partners.jpg',
  },
  {
    key: 101,
    rarity: 2,
    ship: ['Shoukaku', 'Zuikaku'],
    name: 'Tropical Cardiv 5',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/51823456',
      status: 200,
    },
    file: '2_tropical_cardiv_5',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_tropical_cardiv_5.jpg',
  },
  {
    key: 102,
    rarity: 2,
    ship: ['Akebono'],
    name: 'Twintails Akebono',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/75843566',
      status: 200,
    },
    file: '2_twintails_akebono',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_twintails_akebono.jpg',
  },
  {
    key: 103,
    rarity: 2,
    ship: ['Amagi', 'Katsuragi', 'Unryuu'],
    name: 'Unryuu Sisters',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/706433720538902530',
      status: 200,
    },
    file: '2_unryuu_sisters',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_unryuu_sisters.jpg',
  },
  {
    key: 104,
    rarity: 2,
    ship: ['Hibiki'],
    name: 'Verniy Jelly Roll',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/60421508',
      status: 200,
    },
    file: '2_verniy_jelly_roll',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_verniy_jelly_roll.jpg',
  },
  {
    key: 105,
    rarity: 2,
    ship: ['Graf Zeppelin'],
    name: 'Waterlogged Graf Zeppelin',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/63750218',
      status: 200,
    },
    file: '2_waterlogged_graf_zeppelin',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_waterlogged_graf_zeppelin.jpg',
  },
  {
    key: 106,
    rarity: 2,
    ship: ['Abyssal'],
    name: 'White And Black',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/61695488',
      status: 200,
    },
    file: '2_white_and_black',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_white_and_black.jpg',
  },
  {
    key: 107,
    rarity: 2,
    ship: ['Uzuki', 'Yayoi'],
    name: 'Yayoi And Uzuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/43037678',
      status: 200,
    },
    file: '2_yayoi_and_uzuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_yayoi_and_uzuki.jpg',
  },
  {
    key: 108,
    rarity: 2,
    ship: ['Yukikaze'],
    name: 'Yukikazes Day Off',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1161230468282384385',
      status: 200,
    },
    file: '2_yukikazes_day_off',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_yukikazes_day_off.jpg',
  },
  {
    key: 109,
    rarity: 2,
    ship: ['Akigumo', 'Asashimo', 'Hayashimo', 'Kazagumo', 'Kiyoshimo', 'Makigumo', 'Naganami', 'Takanami', 'Yuugumo'],
    name: 'Yuugumo Class',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/676010015921049604',
      status: 404,
    },
    file: '2_yuugumo_class',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/2_yuugumo_class.jpg',
  },
  {
    key: 110,
    rarity: 1,
    ship: ['Abukuma'],
    name: 'Abukuma',
    source: {
      type: 'nicovideo',
      url: 'https://seiga.nicovideo.jp/seiga/im9144665',
      status: 200,
    },
    file: '1_abukuma',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_abukuma.jpg',
  },
  {
    key: 111,
    rarity: 1,
    ship: ['Abyssal'],
    name: 'Abyssal Headquarters',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/63740665',
      status: 200,
    },
    file: '1_abyssal_headquarters',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_abyssal_headquarters.jpg',
  },
  {
    key: 112,
    rarity: 1,
    ship: ['Akagi', 'Akigumo', 'Mamiya'],
    name: 'Airstrip Sushi Bar',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/52304276',
      status: 200,
    },
    file: '1_airstrip_sushi_bar',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_airstrip_sushi_bar.jpg',
  },
  {
    key: 113,
    rarity: 1,
    ship: ['Akagi'],
    name: 'Akagi-too',
    source: {
      type: '38runy',
      url: 'https://twitter.com/38runy/status/930810266505244672',
      status: 200,
    },
    file: '1_akagi-too',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_akagi-too.jpg',
  },
  {
    key: 114,
    rarity: 1,
    ship: ['Akebono'],
    name: 'Akebono',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/990137929027629056',
      status: 200,
    },
    file: '1_akebono',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_akebono.jpg',
  },
  {
    key: 115,
    rarity: 1,
    ship: ['Akigumo'],
    name: 'Akigumo',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/39672163',
      status: 200,
    },
    file: '1_akigumo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_akigumo.jpg',
  },
  {
    key: 116,
    rarity: 1,
    ship: ['Akitsu Maru'],
    name: 'Akitsu Maru',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40787499',
      status: 200,
    },
    file: '1_akitsu_maru',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_akitsu_maru.jpg',
  },
  {
    key: 117,
    rarity: 1,
    ship: ['Akitsushima'],
    name: 'Akitsushima Lookout',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/73214251',
      status: 200,
    },
    file: '1_akitsushima_lookout',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_akitsushima_lookout.jpg',
  },
  {
    key: 118,
    rarity: 1,
    ship: ['Akizuki'],
    name: 'Akizuki',
    source: {
      type: 'rin7914',
      url: 'https://twitter.com/rin7914/status/536112772967178240',
      status: 200,
    },
    file: '1_akizuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_akizuki.jpg',
  },
  {
    key: 119,
    rarity: 1,
    ship: ['Amatsukaze'],
    name: 'Amatsukaze Pose',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/43258459',
      status: 200,
    },
    file: '1_amatsukaze_pose',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_amatsukaze_pose.jpg',
  },
  {
    key: 120,
    rarity: 1,
    ship: ['Amatsukaze'],
    name: 'Amatsukaze Torpedo Twirl',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54171824',
      status: 200,
    },
    file: '1_amatsukaze_torpedo_twirl',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_amatsukaze_torpedo_twirl.jpg',
  },
  {
    key: 121,
    rarity: 1,
    ship: ['Arashio'],
    name: 'Ara Ara Arashio',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/70987460',
      status: 200,
    },
    file: '1_ara_ara_arashio',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_ara_ara_arashio.jpg',
  },
  {
    key: 122,
    rarity: 1,
    ship: ['Ark Royal'],
    name: 'Ark Royal',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/922048222171820033',
      status: 200,
    },
    file: '1_ark_royal',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_ark_royal.jpg',
  },
  {
    key: 123,
    rarity: 1,
    ship: ['Asagumo'],
    name: 'Asagumo',
    source: {
      type: 'anti_twt',
      url: 'https://twitter.com/anti_twt/status/627102941497851904',
      status: 200,
    },
    file: '1_asagumo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_asagumo.jpg',
  },
  {
    key: 124,
    rarity: 1,
    ship: ['Asashio'],
    name: 'Asashio',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54799878',
      status: 200,
    },
    file: '1_asashio',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_asashio.jpg',
  },
  {
    key: 125,
    rarity: 1,
    ship: ['Ushio'],
    name: 'Bashful Ushio',
    source: {
      type: 'nicovideo',
      url: 'https://seiga.nicovideo.jp/seiga/im4458943',
      status: 200,
    },
    file: '1_bashful_ushio',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_bashful_ushio.jpg',
  },
  {
    key: 126,
    rarity: 1,
    ship: ['Bismarck'],
    name: 'Bismarck',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/43218841',
      status: 200,
    },
    file: '1_bismarck',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_bismarck.jpg',
  },
  {
    key: 127,
    rarity: 1,
    ship: ['Hatsuzuki'],
    name: 'Blushing Hatsuzuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55400832',
      status: 200,
    },
    file: '1_blushing_hatsuzuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_blushing_hatsuzuki.jpg',
  },
  {
    key: 128,
    rarity: 1,
    ship: ['Kongou'],
    name: 'British Invaders',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40385343',
      status: 200,
    },
    file: '1_british_invaders',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_british_invaders.jpg',
  },
  {
    key: 129,
    rarity: 1,
    ship: ['Mikazuki'],
    name: 'Bunny Mikazuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/67083989',
      status: 200,
    },
    file: '1_bunny_mikazuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_bunny_mikazuki.jpg',
  },
  {
    key: 130,
    rarity: 1,
    ship: ['Hatsuzuki'],
    name: 'Bunnysuit Hatsuzuki',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/981184249544888321',
      status: 200,
    },
    file: '1_bunnysuit_hatsuzuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_bunnysuit_hatsuzuki.jpg',
  },
  {
    key: 131,
    rarity: 1,
    ship: ['Hayashimo'],
    name: 'Bunnysuit Hayashimo',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/970680335787704320',
      status: 200,
    },
    file: '1_bunnysuit_hayashimo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_bunnysuit_hayashimo.jpg',
  },
  {
    key: 132,
    rarity: 1,
    ship: ['Zara'],
    name: 'Bunnysuit Zara',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/1149307710023749632',
      status: 200,
    },
    file: '1_bunnysuit_zara',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_bunnysuit_zara.jpg',
  },
  {
    key: 133,
    rarity: 1,
    ship: ['Amagi'],
    name: 'Camouflaged Amagi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48948992',
      status: 200,
    },
    file: '1_camouflaged_amagi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_camouflaged_amagi.jpg',
  },
  {
    key: 134,
    rarity: 1,
    ship: ['Shoukaku', 'Zuikaku'],
    name: 'Cardiv 5 Sundresses',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/44552533',
      status: 200,
    },
    file: '1_cardiv_5_sundresses',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_cardiv_5_sundresses.jpg',
  },
  {
    key: 135,
    rarity: 1,
    ship: ['Amagi'],
    name: 'Carrier Amagi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/60508045',
      status: 200,
    },
    file: '1_carrier_amagi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_carrier_amagi.jpg',
  },
  {
    key: 136,
    rarity: 1,
    ship: ['Chitose'],
    name: 'Carrier Chitose',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53149578',
      status: 200,
    },
    file: '1_carrier_chitose',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_carrier_chitose.jpg',
  },
  {
    key: 137,
    rarity: 1,
    ship: ['Unryuu'],
    name: 'Carrier Unryuu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/45961964',
      status: 200,
    },
    file: '1_carrier_unryuu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_carrier_unryuu.jpg',
  },
  {
    key: 138,
    rarity: 1,
    ship: ['Zuihou'],
    name: 'Carrier Zuihou',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/42678429',
      status: 200,
    },
    file: '1_carrier_zuihou',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_carrier_zuihou.jpg',
  },
  {
    key: 139,
    rarity: 1,
    ship: ['Hibiki'],
    name: 'Catgirl Hibiki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/62943298',
      status: 200,
    },
    file: '1_catgirl_hibiki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_catgirl_hibiki.jpg',
  },
  {
    key: 140,
    rarity: 1,
    ship: ['Chiyoda'],
    name: 'Chiyoda',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/52440949',
      status: 200,
    },
    file: '1_chiyoda',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_chiyoda.jpg',
  },
  {
    key: 141,
    rarity: 1,
    ship: ['Naka'],
    name: 'Cleaning Duty Naka',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/47265666',
      status: 200,
    },
    file: '1_cleaning_duty_naka',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_cleaning_duty_naka.jpg',
  },
  {
    key: 142,
    rarity: 1,
    ship: ['Colorado'],
    name: 'Colorado',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1182289073538400257',
      status: 200,
    },
    file: '1_colorado',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_colorado.jpg',
  },
  {
    key: 143,
    rarity: 1,
    ship: ['Amatsukaze'],
    name: 'Common Amatsukaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/60256390',
      status: 200,
    },
    file: '1_common_amatsukaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_common_amatsukaze.jpg',
  },
  {
    key: 144,
    rarity: 1,
    ship: ['Admiral', 'Kazagumo'],
    name: 'Cooling Off In A Raft',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58769396',
      status: 200,
    },
    file: '1_cooling_off_in_a_raft',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_cooling_off_in_a_raft.jpg',
  },
  {
    key: 145,
    rarity: 1,
    ship: ['Matsuwa'],
    name: 'Crybaby Matsuwa',
    source: {
      type: 'nicovideo',
      url: 'https://seiga.nicovideo.jp/seiga/im6992679',
      status: 200,
    },
    file: '1_crybaby_matsuwa',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_crybaby_matsuwa.jpg',
  },
  {
    key: 146,
    rarity: 1,
    ship: ['Yukikaze'],
    name: 'Day Off',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76606294',
      status: 404,
    },
    file: '1_day_off',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_day_off.jpg',
  },
  {
    key: 147,
    rarity: 1,
    ship: ['Kasuga Maru'],
    name: 'Escort Carrier Shinyou',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/70717860',
      status: 200,
    },
    file: '1_escort_carrier_shinyou',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_escort_carrier_shinyou.jpg',
  },
  {
    key: 148,
    rarity: 1,
    ship: ['Kasuga Maru'],
    name: 'Escort Carrier Taiyou',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1174703979504132096',
      status: 200,
    },
    file: '1_escort_carrier_taiyou',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_escort_carrier_taiyou.jpg',
  },
  {
    key: 149,
    rarity: 1,
    ship: ['Etorofu'],
    name: 'Etorofu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/62892380',
      status: 404,
    },
    file: '1_etorofu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_etorofu.jpg',
  },
  {
    key: 150,
    rarity: 1,
    ship: ['I-26'],
    name: 'Finding Nimu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58415973',
      status: 200,
    },
    file: '1_finding_nimu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_finding_nimu.jpg',
  },
  {
    key: 151,
    rarity: 1,
    ship: ['Fubuki'],
    name: 'Fubuki',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1175045001400569856',
      status: 200,
    },
    file: '1_fubuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_fubuki.jpg',
  },
  {
    key: 152,
    rarity: 1,
    ship: ['Fumizuki'],
    name: 'Fumizuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/47844063',
      status: 200,
    },
    file: '1_fumizuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_fumizuki.jpg',
  },
  {
    key: 153,
    rarity: 1,
    ship: ['Gambier Bay'],
    name: 'Gambier Bay',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/974284865200795650',
      status: 404,
    },
    file: '1_gambier_bay',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_gambier_bay.jpg',
  },
  {
    key: 154,
    rarity: 1,
    ship: ['Akebono'],
    name: 'Geared Up Akebono',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/41777927',
      status: 200,
    },
    file: '1_geared_up_akebono',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_geared_up_akebono.jpg',
  },
  {
    key: 155,
    rarity: 1,
    ship: ['Amatsukaze'],
    name: 'Gift From Amatsukaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/73202509',
      status: 200,
    },
    file: '1_gift_from_amatsukaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_gift_from_amatsukaze.jpg',
  },
  {
    key: 156,
    rarity: 1,
    ship: ['Giuseppe Garibaldi'],
    name: 'Giuseppe Garibaldi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/74898871',
      status: 200,
    },
    file: '1_giuseppe_garibaldi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_giuseppe_garibaldi.jpg',
  },
  {
    key: 157,
    rarity: 1,
    ship: ['Gotland'],
    name: 'Gotland',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/71658227',
      status: 200,
    },
    file: '1_gotland',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_gotland.jpg',
  },
  {
    key: 158,
    rarity: 1,
    ship: ['Wakaba'],
    name: 'Gun Wakaba',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55881810',
      status: 200,
    },
    file: '1_gun_wakaba',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_gun_wakaba.jpg',
  },
  {
    key: 159,
    rarity: 1,
    ship: ['Hamakaze'],
    name: 'Hamakaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/42601052',
      status: 404,
    },
    file: '1_hamakaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_hamakaze.jpg',
  },
  {
    key: 160,
    rarity: 1,
    ship: ['Yayoi'],
    name: 'Happy Yayoi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/65582350',
      status: 200,
    },
    file: '1_happy_yayoi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_happy_yayoi.jpg',
  },
  {
    key: 161,
    rarity: 1,
    ship: ['Haruna'],
    name: 'Haruna Crumpets',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58699642',
      status: 200,
    },
    file: '1_haruna_crumpets',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_haruna_crumpets.jpg',
  },
  {
    key: 162,
    rarity: 1,
    ship: ['Haruna'],
    name: 'Haruna Volley',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/50158780',
      status: 200,
    },
    file: '1_haruna_volley',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_haruna_volley.jpg',
  },
  {
    key: 163,
    rarity: 1,
    ship: ['Harusame'],
    name: 'Harusame',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/45456249',
      status: 200,
    },
    file: '1_harusame',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_harusame.jpg',
  },
  {
    key: 164,
    rarity: 1,
    ship: ['Hatsukaze'],
    name: 'Hatsukaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/43395147',
      status: 200,
    },
    file: '1_hatsukaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_hatsukaze.jpg',
  },
  {
    key: 165,
    rarity: 1,
    ship: ['Kumano'],
    name: 'Heavy Cruiser Kumano',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/38943009',
      status: 200,
    },
    file: '1_heavy_cruiser_kumano',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_heavy_cruiser_kumano.jpg',
  },
  {
    key: 166,
    rarity: 1,
    ship: ['Suzuya'],
    name: 'Heavy Cruiser Suzuya',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40260687',
      status: 200,
    },
    file: '1_heavy_cruiser_suzuya',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_heavy_cruiser_suzuya.jpg',
  },
  {
    key: 167,
    rarity: 1,
    ship: ['Hiei'],
    name: 'Hiei Baked Sweets',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58699642',
      status: 200,
    },
    file: '1_hiei_baked_sweets',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_hiei_baked_sweets.jpg',
  },
  {
    key: 168,
    rarity: 1,
    ship: ['Asashio'],
    name: 'Idea Bulb',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76047909',
      status: 200,
    },
    file: '1_idea_bulb',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_idea_bulb.jpg',
  },
  {
    key: 169,
    rarity: 1,
    ship: ['Fumizuki'],
    name: 'Innocent Fumizuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48408354',
      status: 200,
    },
    file: '1_innocent_fumizuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_innocent_fumizuki.jpg',
  },
  {
    key: 170,
    rarity: 1,
    ship: ['Isokaze'],
    name: 'Isokaze',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1073933633688236032',
      status: 200,
    },
    file: '1_isokaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_isokaze.jpg',
  },
  {
    key: 171,
    rarity: 1,
    ship: ['Kaga'],
    name: 'Kaga Victory Pose',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/52335768',
      status: 200,
    },
    file: '1_kaga_victory_pose',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kaga_victory_pose.jpg',
  },
  {
    key: 172,
    rarity: 1,
    ship: ['Kaga'],
    name: 'Kagatoo',
    source: {
      type: '38runy',
      url: 'https://twitter.com/38runy/status/930810266505244672',
      status: 200,
    },
    file: '1_kagatoo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kagatoo.jpg',
  },
  {
    key: 173,
    rarity: 1,
    ship: ['Kasumi'],
    name: 'Kasumi Model B',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54852639',
      status: 404,
    },
    file: '1_kasumi_model_b',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kasumi_model_b.jpg',
  },
  {
    key: 174,
    rarity: 1,
    ship: ['Katsuragi'],
    name: 'Katsuragi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/50082396',
      status: 200,
    },
    file: '1_katsuragi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_katsuragi.jpg',
  },
  {
    key: 175,
    rarity: 1,
    ship: ['Kikuzuki'],
    name: 'Kikuzuki',
    source: {
      type: 'danbooru',
      url: 'https://danbooru.donmai.us/posts/1732373',
      status: 200,
    },
    file: '1_kikuzuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kikuzuki.jpg',
  },
  {
    key: 176,
    rarity: 1,
    ship: ['Agano'],
    name: 'Kirari-n Agano',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53320096',
      status: 200,
    },
    file: '1_kirari-n_agano',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kirari-n_agano.jpg',
  },
  {
    key: 177,
    rarity: 1,
    ship: ['Kirishima'],
    name: 'Kirishima Shortcake',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/58699642',
      status: 200,
    },
    file: '1_kirishima_shortcake',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kirishima_shortcake.jpg',
  },
  {
    key: 178,
    rarity: 1,
    ship: ['Kitakami', 'Ooi'],
    name: 'Kitakami And Ooi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54076616',
      status: 200,
    },
    file: '1_kitakami_and_ooi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kitakami_and_ooi.jpg',
  },
  {
    key: 179,
    rarity: 1,
    ship: ['Kongou'],
    name: 'Kongou Tea Time',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/56004360',
      status: 200,
    },
    file: '1_kongou_tea_time',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_kongou_tea_time.jpg',
  },
  {
    key: 180,
    rarity: 1,
    ship: ['Z1'],
    name: 'Leberecht Maass',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/42434608',
      status: 200,
    },
    file: '1_leberecht_maass',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_leberecht_maass.jpg',
  },
  {
    key: 181,
    rarity: 1,
    ship: ['Libeccio'],
    name: 'Libeccio',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/51918496',
      status: 200,
    },
    file: '1_libeccio',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_libeccio.jpg',
  },
  {
    key: 182,
    rarity: 1,
    ship: ['Fumizuki'],
    name: 'Lovely Fumizuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48159048',
      status: 200,
    },
    file: '1_lovely_fumizuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_lovely_fumizuki.jpg',
  },
  {
    key: 183,
    rarity: 1,
    ship: ['Luigi Torelli'],
    name: 'Luigi Torelli',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/64534816',
      status: 200,
    },
    file: '1_luigi_torelli',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_luigi_torelli.jpg',
  },
  {
    key: 184,
    rarity: 1,
    ship: ['Shigure'],
    name: 'Maid Shigure',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/49954862',
      status: 200,
    },
    file: '1_maid_shigure',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_maid_shigure.jpg',
  },
  {
    key: 185,
    rarity: 1,
    ship: ['Taihou'],
    name: 'Maid Taihou',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/69147314',
      status: 200,
    },
    file: '1_maid_taihou',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_maid_taihou.jpg',
  },
  {
    key: 186,
    rarity: 1,
    ship: ['Hibiki'],
    name: 'Marine Hibiki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/49031075',
      status: 200,
    },
    file: '1_marine_hibiki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_marine_hibiki.jpg',
  },
  {
    key: 187,
    rarity: 1,
    ship: ['Z3'],
    name: 'Max Schultz',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/42614082',
      status: 200,
    },
    file: '1_max_schultz',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_max_schultz.jpg',
  },
  {
    key: 188,
    rarity: 1,
    ship: ['Murakumo'],
    name: 'Melancholy Murakumo',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/779917033597054976',
      status: 200,
    },
    file: '1_melancholy_murakumo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_melancholy_murakumo.jpg',
  },
  {
    key: 189,
    rarity: 1,
    ship: ['Michishio'],
    name: 'Michishio',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/66082789',
      status: 200,
    },
    file: '1_michishio',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_michishio.jpg',
  },
  {
    key: 190,
    rarity: 1,
    ship: ['Mikazuki'],
    name: 'Mikazuki Bliss',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/64656842',
      status: 200,
    },
    file: '1_mikazuki_bliss',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_mikazuki_bliss.jpg',
  },
  {
    key: 191,
    rarity: 1,
    ship: ['Minazuki'],
    name: 'Minazuki Pose',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/63489105',
      status: 200,
    },
    file: '1_minazuki_pose',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_minazuki_pose.jpg',
  },
  {
    key: 192,
    rarity: 1,
    ship: ['Minegumo'],
    name: 'Minegumo',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76665337',
      status: 200,
    },
    file: '1_minegumo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_minegumo.jpg',
  },
  {
    key: 193,
    rarity: 1,
    ship: ['Mochizuki'],
    name: 'Mochizuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/59119832',
      status: 200,
    },
    file: '1_mochizuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_mochizuki.jpg',
  },
  {
    key: 194,
    rarity: 1,
    ship: ['Maruyu'],
    name: 'Mole-chan Maruyu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/40667252',
      status: 200,
    },
    file: '1_mole-chan_maruyu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_mole-chan_maruyu.jpg',
  },
  {
    key: 195,
    rarity: 1,
    ship: ['Iowa'],
    name: 'Most Volleyball Iowa',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55428020',
      status: 200,
    },
    file: '1_most_volleyball_iowa',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_most_volleyball_iowa.jpg',
  },
  {
    key: 196,
    rarity: 1,
    ship: ['Murakumo'],
    name: 'Murakumos Bikini',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/1015141851219705856',
      status: 200,
    },
    file: '1_murakumos_bikini',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_murakumos_bikini.jpg',
  },
  {
    key: 197,
    rarity: 1,
    ship: ['Murasame'],
    name: 'Murasame',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1087822729103855616',
      status: 200,
    },
    file: '1_murasame',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_murasame.jpg',
  },
  {
    key: 198,
    rarity: 1,
    ship: ['Nagatsuki'],
    name: 'Nagatsuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/74756460',
      status: 200,
    },
    file: '1_nagatsuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_nagatsuki.jpg',
  },
  {
    key: 199,
    rarity: 1,
    ship: ['Nelson'],
    name: 'Nelson',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/71157827',
      status: 200,
    },
    file: '1_nelson',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_nelson.jpg',
  },
  {
    key: 200,
    rarity: 1,
    ship: ['Abyssal'],
    name: 'Northern Princess',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/54218556',
      status: 200,
    },
    file: '1_northern_princess',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_northern_princess.jpg',
  },
  {
    key: 201,
    rarity: 1,
    ship: ['Abyssal'],
    name: 'Northern Princess Sisters',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/74903603',
      status: 200,
    },
    file: '1_northern_princess_sisters',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_northern_princess_sisters.jpg',
  },
  {
    key: 202,
    rarity: 1,
    ship: ['Noshiro'],
    name: 'Noshiro',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/938055881614245888',
      status: 200,
    },
    file: '1_noshiro',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_noshiro.jpg',
  },
  {
    key: 203,
    rarity: 1,
    ship: ['Nagatsuki'],
    name: 'Nyagatsuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/73963958',
      status: 200,
    },
    file: '1_nyagatsuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_nyagatsuki.jpg',
  },
  {
    key: 204,
    rarity: 1,
    ship: ['Abyssal'],
    name: 'Oni Tsundere',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/69598518',
      status: 200,
    },
    file: '1_oni_tsundere',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_oni_tsundere.jpg',
  },
  {
    key: 205,
    rarity: 1,
    ship: ['Ooshio'],
    name: 'Ooshio',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1149770808715169792',
      status: 200,
    },
    file: '1_ooshio',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_ooshio.jpg',
  },
  {
    key: 206,
    rarity: 1,
    ship: ['Sendai'],
    name: 'Pre-night Battle Smile',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/66181233',
      status: 200,
    },
    file: '1_pre-night_battle_smile',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_pre-night_battle_smile.jpg',
  },
  {
    key: 207,
    rarity: 1,
    ship: ['Ooi'],
    name: 'Present From Ooi',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/963416967318192128',
      status: 200,
    },
    file: '1_present_from_ooi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_present_from_ooi.jpg',
  },
  {
    key: 208,
    rarity: 1,
    ship: ['Abyssal', 'Admiral'],
    name: 'Princess Meets Prince',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/45983656',
      status: 200,
    },
    file: '1_princess_meets_prince',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_princess_meets_prince.jpg',
  },
  {
    key: 209,
    rarity: 1,
    ship: ['Prinz Eugen'],
    name: 'Prinz Eugen',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/47279550',
      status: 200,
    },
    file: '1_prinz_eugen',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_prinz_eugen.jpg',
  },
  {
    key: 210,
    rarity: 1,
    ship: ['Ro-500'],
    name: 'Ro-chan',
    source: {
      type: 'atutoku',
      url: 'https://twitter.com/atutoku/status/1169637583090905088',
      status: 200,
    },
    file: '1_ro-chan',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_ro-chan.jpg',
  },
  {
    key: 211,
    rarity: 1,
    ship: ['Sado'],
    name: 'Sado-sama',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1004733604751015936',
      status: 200,
    },
    file: '1_sado-sama',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sado-sama.jpg',
  },
  {
    key: 212,
    rarity: 1,
    ship: ['Samidare'],
    name: 'Samidares Fav Food',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/72059709',
      status: 200,
    },
    file: '1_samidares_fav_food',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_samidares_fav_food.jpg',
  },
  {
    key: 213,
    rarity: 1,
    ship: ['Samuel B. Roberts'],
    name: 'Samuel B Roberts',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/68425559',
      status: 200,
    },
    file: '1_samuel_b_roberts',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_samuel_b_roberts.jpg',
  },
  {
    key: 214,
    rarity: 1,
    ship: ['Saratoga'],
    name: 'Saratoga Of The Orient',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/836955072479158273',
      status: 200,
    },
    file: '1_saratoga_of_the_orient',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_saratoga_of_the_orient.jpg',
  },
  {
    key: 215,
    rarity: 1,
    ship: ['Saratoga'],
    name: 'Saratogas Air Support',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/62977369',
      status: 200,
    },
    file: '1_saratogas_air_support',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_saratogas_air_support.jpg',
  },
  {
    key: 216,
    rarity: 1,
    ship: ['Satsuki'],
    name: 'Satsuki',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/55697036',
      status: 200,
    },
    file: '1_satsuki',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_satsuki.jpg',
  },
  {
    key: 217,
    rarity: 1,
    ship: ['Sazanami'],
    name: 'Sazanami',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/38213308',
      status: 200,
    },
    file: '1_sazanami',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sazanami.jpg',
  },
  {
    key: 218,
    rarity: 1,
    ship: ['Sendai'],
    name: 'Sendai Kai Ni',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/75748431',
      status: 200,
    },
    file: '1_sendai_kai_ni',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sendai_kai_ni.jpg',
  },
  {
    key: 219,
    rarity: 1,
    ship: ['Sendai'],
    name: 'Sendai Strike',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/62978912',
      status: 200,
    },
    file: '1_sendai_strike',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sendai_strike.jpg',
  },
  {
    key: 220,
    rarity: 1,
    ship: ['Sendai'],
    name: 'Sendais Shark Plushie',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/75378486',
      status: 200,
    },
    file: '1_sendais_shark_plushie',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sendais_shark_plushie.jpg',
  },
  {
    key: 221,
    rarity: 1,
    ship: ['Sakawa'],
    name: 'Serious Sakawa',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/44252774',
      status: 200,
    },
    file: '1_serious_sakawa',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_serious_sakawa.jpg',
  },
  {
    key: 222,
    rarity: 1,
    ship: ['Samidare', 'Shigure'],
    name: 'Shigure And Samidare',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/68931142',
      status: 200,
    },
    file: '1_shigure_and_samidare',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_shigure_and_samidare.jpg',
  },
  {
    key: 223,
    rarity: 1,
    ship: ['Shigure'],
    name: 'Shigures Launch',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/74799649',
      status: 200,
    },
    file: '1_shigures_launch',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_shigures_launch.jpg',
  },
  {
    key: 224,
    rarity: 1,
    ship: ['I-400', 'I-401'],
    name: 'Shion And Shioi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/66451352',
      status: 200,
    },
    file: '1_shion_and_shioi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_shion_and_shioi.jpg',
  },
  {
    key: 225,
    rarity: 1,
    ship: ['Taigei'],
    name: 'Shopping Duty Taigei',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/47251593',
      status: 200,
    },
    file: '1_shopping_duty_taigei',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_shopping_duty_taigei.jpg',
  },
  {
    key: 226,
    rarity: 1,
    ship: ['Shoukaku'],
    name: 'Shoukakus New Power',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53670589',
      status: 200,
    },
    file: '1_shoukakus_new_power',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_shoukakus_new_power.jpg',
  },
  {
    key: 227,
    rarity: 1,
    ship: ['Akatsuki', 'Hibiki', 'Ikazuchi', 'Inazuma'],
    name: 'Sixth Destroyer Cornvision',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/75863234',
      status: 200,
    },
    file: '1_sixth_destroyer_cornvision',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sixth_destroyer_cornvision.jpg',
  },
  {
    key: 228,
    rarity: 1,
    ship: ['Akagi', 'Kaga'],
    name: 'Sleeping Soundly',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/44915183',
      status: 200,
    },
    file: '1_sleeping_soundly',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sleeping_soundly.jpg',
  },
  {
    key: 229,
    rarity: 1,
    ship: ['Murasame'],
    name: 'Snowy Murasame',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1091346115935391744',
      status: 200,
    },
    file: '1_snowy_murasame',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_snowy_murasame.jpg',
  },
  {
    key: 230,
    rarity: 1,
    ship: ['Yamakaze'],
    name: 'Summer Yamakaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/70107233',
      status: 200,
    },
    file: '1_summer_yamakaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_summer_yamakaze.jpg',
  },
  {
    key: 231,
    rarity: 1,
    ship: ['Jintsuu'],
    name: 'Sunset Jintsuu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53381177',
      status: 404,
    },
    file: '1_sunset_jintsuu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sunset_jintsuu.jpg',
  },
  {
    key: 232,
    rarity: 1,
    ship: ['Yahagi'],
    name: 'Sunset Yahagi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/74078181',
      status: 200,
    },
    file: '1_sunset_yahagi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sunset_yahagi.jpg',
  },
  {
    key: 233,
    rarity: 1,
    ship: ['Zuikaku'],
    name: 'Sunset Zuikaku',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/47595784',
      status: 200,
    },
    file: '1_sunset_zuikaku',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_sunset_zuikaku.jpg',
  },
  {
    key: 234,
    rarity: 1,
    ship: ['Suzutsuki'],
    name: 'Suzu-squash',
    source: {
      type: 'eber_accebeR',
      url: 'https://twitter.com/eber_accebeR/status/933714586401828864',
      status: 200,
    },
    file: '1_suzu-squash',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_suzu-squash.jpg',
  },
  {
    key: 235,
    rarity: 1,
    ship: ['Yura'],
    name: 'Swimsuit Yura',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/65131273',
      status: 200,
    },
    file: '1_swimsuit_yura',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_swimsuit_yura.jpg',
  },
  {
    key: 236,
    rarity: 1,
    ship: ['Z1'],
    name: 'Swimsuit Z1',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1165596958209101824',
      status: 200,
    },
    file: '1_swimsuit_z1',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_swimsuit_z1.jpg',
  },
  {
    key: 237,
    rarity: 1,
    ship: ['Z3'],
    name: 'Swimsuit Z3',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/1005041569311756289',
      status: 200,
    },
    file: '1_swimsuit_z3',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_swimsuit_z3.jpg',
  },
  {
    key: 238,
    rarity: 1,
    ship: ['Tanikaze'],
    name: 'Tanikaze',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/44445238',
      status: 404,
    },
    file: '1_tanikaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_tanikaze.jpg',
  },
  {
    key: 239,
    rarity: 1,
    ship: ['Tatsuta'],
    name: 'Tatsuta Twirl',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/63189457',
      status: 200,
    },
    file: '1_tatsuta_twirl',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_tatsuta_twirl.jpg',
  },
  {
    key: 240,
    rarity: 1,
    ship: ['Kongou'],
    name: 'Tea Time Desu',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/49383627',
      status: 200,
    },
    file: '1_tea_time_desu',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_tea_time_desu.jpg',
  },
  {
    key: 241,
    rarity: 1,
    ship: ['Mogami'],
    name: 'The Last Mogami',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/57377544',
      status: 200,
    },
    file: '1_the_last_mogami',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_the_last_mogami.jpg',
  },
  {
    key: 242,
    rarity: 1,
    ship: ['I-58'],
    name: 'The Orel Cruise',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48472221',
      status: 200,
    },
    file: '1_the_orel_cruise',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_the_orel_cruise.jpg',
  },
  {
    key: 243,
    rarity: 1,
    ship: ['Tone'],
    name: 'Tone Kai Ni',
    source: {
      type: '6thbody',
      url: 'https://twitter.com/6thbody/status/875941321243975680',
      status: 200,
    },
    file: '1_tone_kai_ni',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_tone_kai_ni.jpg',
  },
  {
    key: 244,
    rarity: 1,
    ship: ['Kiso'],
    name: 'Torpedo Cruiser Kiso',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/930443699196108800',
      status: 200,
    },
    file: '1_torpedo_cruiser_kiso',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_torpedo_cruiser_kiso.jpg',
  },
  {
    key: 245,
    rarity: 1,
    ship: ['Tsushima'],
    name: 'Tsushima',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/66936067',
      status: 200,
    },
    file: '1_tsushima',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_tsushima.jpg',
  },
  {
    key: 246,
    rarity: 1,
    ship: ['Oboro'],
    name: 'Umbrella Oboro',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/50548952',
      status: 404,
    },
    file: '1_umbrella_oboro',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_umbrella_oboro.jpg',
  },
  {
    key: 247,
    rarity: 1,
    ship: ['Unryuu'],
    name: 'Unryuu Or Two',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/72621943',
      status: 200,
    },
    file: '1_unryuu_or_two',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_unryuu_or_two.jpg',
  },
  {
    key: 248,
    rarity: 1,
    ship: ['Urakaze'],
    name: 'Urakaze',
    source: {
      type: 'twitter',
      url: 'https://twitter.com/i/web/status/807528267754283009',
      status: 200,
    },
    file: '1_urakaze',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_urakaze.jpg',
  },
  {
    key: 249,
    rarity: 1,
    ship: ['Uzuki'],
    name: 'Uzuki Pyon',
    source: {
      type: 'nicovideo',
      url: 'https://seiga.nicovideo.jp/seiga/im9671014',
      status: 200,
    },
    file: '1_uzuki_pyon',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_uzuki_pyon.jpg',
  },
  {
    key: 250,
    rarity: 1,
    ship: ['Warspite'],
    name: 'Warspites Warmsmile',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/59516378',
      status: 200,
    },
    file: '1_warspites_warmsmile',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_warspites_warmsmile.jpg',
  },
  {
    key: 251,
    rarity: 1,
    ship: ['Suzuya'],
    name: 'Winking Suzuya',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/65592662',
      status: 200,
    },
    file: '1_winking_suzuya',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_winking_suzuya.jpg',
  },
  {
    key: 252,
    rarity: 1,
    ship: ['Yamagumo'],
    name: 'Yamagumo',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48429215',
      status: 200,
    },
    file: '1_yamagumo',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_yamagumo.jpg',
  },
  {
    key: 253,
    rarity: 1,
    ship: ['Yahagi'],
    name: 'Yamatos Twin Sister Yahagi',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/69620222',
      status: 200,
    },
    file: '1_yamatos_twin_sister_yahagi',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_yamatos_twin_sister_yahagi.jpg',
  },
  {
    key: 254,
    rarity: 1,
    ship: ['Kongou'],
    name: 'Yes Admiral',
    source: {
      type: '_konkito',
      url: 'https://twitter.com/_konkito/status/1163813448397885442',
      status: 200,
    },
    file: '1_yes_admiral',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_yes_admiral.jpg',
  },
  {
    key: 255,
    rarity: 1,
    ship: ['Yuudachi'],
    name: 'Yuudachi Grin',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/68186257',
      status: 200,
    },
    file: '1_yuudachi_grin',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_yuudachi_grin.jpg',
  },
  {
    key: 256,
    rarity: 1,
    ship: ['Yuudachi'],
    name: 'Yuudachi Kai Ni',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/57420202',
      status: 200,
    },
    file: '1_yuudachi_kai_ni',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_yuudachi_kai_ni.jpg',
  },
  {
    key: 257,
    rarity: 1,
    ship: ['Yuudachi'],
    name: 'Yuudachi Volley',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/76324460',
      status: 200,
    },
    file: '1_yuudachi_volley',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_yuudachi_volley.jpg',
  },
  {
    key: 258,
    rarity: 1,
    ship: ['Akebono', 'Zuihou'],
    name: 'Zuihoubono',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/48186690',
      status: 200,
    },
    file: '1_zuihoubono',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_zuihoubono.jpg',
  },
  {
    key: 259,
    rarity: 1,
    ship: ['Zuikaku'],
    name: 'Zuikakus New Power',
    source: {
      type: 'pixiv',
      url: 'https://www.pixiv.net/artworks/53670589',
      status: 200,
    },
    file: '1_zuikakus_new_power',
    image: 'https://amusementclub.nyc3.cdn.digitaloceanspaces.com/cards/kancolle/1_zuikakus_new_power.jpg',
  },
]

export default data
